### ISSUE TITLE
vector<bool> support

### ISSUE THREAD

**Issue by rccreager** [dguest/ttree2hdf5#3]
I'm having some trouble running this over the b-jet-trigger group's tuples (/afs/cern.ch/work/l/losterzo/public/bjettrigger/). It contains a vector<bool>, which isn't supported. Otherwise it runs great :)

Could support be added?

Thanks,
Rachael

**Comment by dguest** [comment]
Should be pretty easy but it will take a few minutes: I'll look into it tomorrow.

**Comment by dguest** [comment]
Hi @rccreager, I made some changes that should support this but I haven't tested them on any files with `vector<bool>` branches yet. Give it a try if you feel adventurous.

**Comment by rccreager** [comment]
OK, I tried it out, and I still get the same result -- the branches before the vector<bool> are included, but that's it. I made sure to clean and recompile.

**Comment by rccreager** [comment]
It works!! Thank you :)
