### ISSUE TITLE
Build on lxplus

### ISSUE THREAD

**Issue by gerbaudo** [dguest/ttree2hdf5#7]
Hi @dguest 

Thank you for this code!
I was trying to build it on lxplus but it complains about the HDF5 version.
For some reason cmake doesn't seem to pick up your HDF5 build. Am I missing something?
Thanks!
Davide

-------------
```
$ hostname 
lxplus050.cern.ch

git clone git@github.com:dguest/ttree2hdf5.git
cd ttree2hdf5/
source setup/atlas-cvmfs.sh
mkdir build
cd build
HDF5_ROOT=/afs/cern.ch/user/d/dguest/afswork/public/hdf5/hdf5-1.8.19/install/
HDF5_ROOT=${HDF5_ROOT} cmake ..

<...snip...>
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
CMake Error at /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HDF5: Found unsuitable version "1.8.5.1", but required is at
  least "1.8.12" (found
  /usr/lib64/libhdf5_cpp.so;/usr/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libm.so)
Call Stack (most recent call first):
  /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:375 (_FPHSA_FAILURE_MESSAGE)
  /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.8.1/Linux-x86_64/share/cmake-3.8/Modules/FindHDF5.cmake:822 (find_package_handle_standard_args)
  CMakeLists.txt:69 (find_package)
```

**Comment by dguest** [comment]
Hmm, yes the annoying thing is that there's a version of HDF5 on lxplus, but it's quite old. I was probably running it with the BUILTIN_HDF5 option when I got it running before. I'll try to fix this.

**Comment by dguest** [comment]
Hmm, now I'm not sure what the problem is. I was able to reproduce the problem and pushed a new commit that I thought fixed it, but now I can't reproduce the original problem even if I check out the former HEAD (`0ac5621`). Maybe CVMFS is behaving weird? Can you try compiling with the current `master` branch?

**Comment by gerbaudo** [comment]
Thanks! now it compiles fine.
It also runs fine with an example tree from the root tutorials
```
root -x -q -b `root-config --prefix`/tutorials/tree/tree1.C
./build/ttree2hdf5  tree1.root -o tree1.hd5
```
but it crashes with a larger tree (I paste the output  at the link below in case it's useful):
http://cern.ch/stikked/view/735212fe

Thank you!
I'll keep playing with it an report here if I see anything odd.

**Comment by dguest** [comment]
Hey, see here: 

https://stackoverflow.com/a/21707820

it seems that HDF5 is limited to about 2000 columns :(

Fortunately, you can filter the branches with a regex (try the `-h`) option to learn more. It's a bit of an annoying limitation, but to be honest I didn't write this library to write out our full datasets, I just wanted a way to make derived data for machine learning and stuff.

**Comment by gerbaudo** [comment]
Good to know, thank you!
I can live with 2000 columns :-) that was just the first tree I had at hand for testing.

**Comment by dguest** [comment]
OK, thanks for being a guinea pig. If you have any other issues let me know, and of course pull requests are always welcome!
